"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['controller.png','history.png','restart.png','rock.png','paper.png','scissor.png','settings.png']
OPTIONS = {
    'iconfile':'rock-paper-scissors.ico'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)